"""initial schema

Revision ID: 3ee0c9e2add3
Revises: 
Create Date: 2026-02-25 20:18:02.927092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee0c9e2add3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_nexus', sa.Text(), nullable=True),
    sa.Column('name_rmp', sa.Text(), nullable=True),
    sa.Column('rmp_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rmp_id')
    )
    op.create_table('gaucho_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weights_used', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grade_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('a_plus', sa.Integer(), nullable=True),
    sa.Column('a', sa.Integer(), nullable=True),
    sa.Column('a_minus', sa.Integer(), nullable=True),
    sa.Column('b_plus', sa.Integer(), nullable=True),
    sa.Column('b', sa.Integer(), nullable=True),
    sa.Column('b_minus', sa.Integer(), nullable=True),
    sa.Column('c_plus', sa.Integer(), nullable=True),
    sa.Column('c', sa.Integer(), nullable=True),
    sa.Column('c_minus', sa.Integer(), nullable=True),
    sa.Column('d_plus', sa.Integer(), nullable=True),
    sa.Column('d', sa.Integer(), nullable=True),
    sa.Column('d_minus', sa.Integer(), nullable=True),
    sa.Column('f', sa.Integer(), nullable=True),
    sa.Column('avg_gpa', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rmp_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('overall_quality', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('would_take_again_pct', sa.Float(), nullable=True),
    sa.Column('num_ratings', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rmp_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rmp_rating_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rmp_rating_id'], ['rmp_ratings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rmp_comments')
    op.drop_table('rmp_ratings')
    op.drop_table('grade_distributions')
    op.drop_table('gaucho_scores')
    op.drop_table('professors')
    op.drop_table('courses')
    # ### end Alembic commands ###
